#!/usr/bin/env python3
"""
sync_vocab.py — fold ontology/odor_terms.tsv into review.html's VOCAB array.

    python3 pipeline/sync_vocab.py            # report the drift, change nothing
    python3 pipeline/sync_vocab.py --write    # rewrite the VOCAB line, backup first

WHY THIS EXISTS
---------------
review.html is opened as a FILE, with no server behind it, so it cannot read
odor_terms.tsv at run time — the vocabulary has to be embedded in the page. Embedded
means a second copy, and a second copy drifts. On 2026-09-10 it had: 110 forms in the
page against 119 in the ontology, with 46 ontology forms invisible to the queue's
productive-ordering, including `sandal` and `animalistic` — added 2026-09-05 for tags
that were two molecules short. The rows that would have moved those tags were the rows
the ordering could not see.

This is the third instance of the same failure in one week (harvest.py stale on Hetzner,
PRODUCTIVE() nearly-reimplemented in status.py). Generating the line beats maintaining
it, and `status.py` warns whenever the two diverge again.

UNION, NOT REPLACEMENT — AND THIS IS THE IMPORTANT PART
-------------------------------------------------------
VOCAB is NOT the tag vocabulary. It is a RECALL HEURISTIC for queue ordering: "might this
sentence be worth reading first". It legitimately holds 37 words that are not tag surface
forms —

    almond, banana, vetiver, ozonic, phenolic, leafy    candidate descriptors the
                                                        ontology has not admitted
    diffusive, radiant, tenacious, transparent          intensity words, which
                                                        REVIEW-RULES.md says are NOT
                                                        descriptors at all

Replacing VOCAB with odor_terms.tsv would DELETE those and shrink the queue — hiding rows
rather than surfacing them. So this takes the UNION. The count can only go up, and a word
that turns out to be useless costs one glance from a reviewer who was going to decide
anyway.

The extra words are kept in the file, not discarded, so a later reader can see that the
breadth was deliberate.
"""
from __future__ import annotations
import importlib.util, json, pathlib, re, sys, time

HERE = pathlib.Path(__file__).resolve().parent
ROOT = HERE.parent
PAGE = HERE / "review.html"

spec = importlib.util.spec_from_file_location("status", HERE / "status.py")
status = importlib.util.module_from_spec(spec)
spec.loader.exec_module(status)


def main() -> int:
    html = PAGE.read_text(encoding="utf-8")
    m = re.search(r"(var\s+VOCAB\s*=\s*)(\[.*?\])(;)", html, re.S)
    if not m:
        sys.exit("could not find the VOCAB array in review.html")

    current = [v.lower() for v in json.loads(m.group(2))]
    onto = sorted(status.load_tags())
    merged = sorted(set(current) | set(onto))

    added = sorted(set(onto) - set(current))
    extra = sorted(set(current) - set(onto))

    print(f"review.html VOCAB   {len(current)}")
    print(f"odor_terms.tsv      {len(onto)}")
    print(f"union               {len(merged)}\n")
    print(f"ADDING {len(added)} ontology forms the queue could not see:")
    print("  " + ", ".join(added) + "\n")
    print(f"KEEPING {len(extra)} page-only forms — recall heuristic, not tags:")
    print("  " + ", ".join(extra) + "\n")

    if "--write" not in sys.argv:
        print("Report only. Add --write to rewrite the line.")
        return 0

    bak = PAGE.with_suffix(f".html.bak-{time.strftime('%Y%m%d-%H%M%S')}")
    bak.write_text(html, encoding="utf-8")

    arr = "[" + ", ".join(json.dumps(w) for w in merged) + "]"
    note = ("  // GENERATED by pipeline/sync_vocab.py — union of ontology/odor_terms.tsv\n"
            "  // and the page's own recall words. Do not hand-edit: re-run the script.\n"
            "  // status.py reports drift between this array and the ontology.\n")
    html = html[:m.start()] + note + m.group(1) + arr + m.group(3) + html[m.end():]
    PAGE.write_text(html, encoding="utf-8")
    print(f"backup  -> {bak.name}")
    print(f"written -> {PAGE.name}  ({len(merged)} forms)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
